name: Hello World Workflow

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build project
      run: |
        npm install
        npm run build
        echo "Hello World"
